### ISSUE TITLE
This was incorrect.

### ISSUE THREAD

**Issue by slymeasy** [kjack9/SynNoMoreEasyEnemies#5]
This was incorrect.

**Comment by kjack9** [comment]
Since all this mod does is change the difficulty of enemies, it can't really cause CTDs. All your trace is saying is that the Body Guard that was somehow involved in your crash was stored in "Syn No More Easy Enemies.esp". That doesn't mean that NMEE is what actually caused the crash though.

In my experience, debugging CTDs in Skyrim is darn near a black art bordering on impossible. That being said, look at any SKSE mods you're using for a more likely culprit in your crash.

I am closing this as invalid. If you find some evidence to suggest that changing the difficult setting of enemies is somehow causing crashes, I would be very interested to hear how that works.

**Comment by slymeasy** [comment]
I noticed that my Synthesis leveled list patcher is overwriting some of NMEE's changes. I create all my Synthesis patches together. Do you think it might help if I create the NMEE patch first and enable it so that my Synthesis leveled list patcher can see it and forward the records?

**Comment by Noggog** [comment]
The load order needs to match the patching order.   If Synthesis is being placed after NMEE so that it could possibly overwrite its changes, then NMEE should be before Synthesis in the LO at the time of patching, too, so that Synthesis considers it when building the patch

Generally, Synth should be run on the LO as you're going to play it.  You shouldn't add things before Synthesis.esp that weren't there when the patch was made

**Comment by slymeasy** [comment]
> The load order needs to match the patching order. If Synthesis is being placed after NMEE so that it could possibly overwrite its changes, then NMEE should be before Synthesis in the LO at the time of patching, too, so that Synthesis considers it when building the patch
> 
> Generally, Synth should be run on the LO as you're going to play it. You shouldn't add things before Synthesis.esp that weren't there when the patch was made

I use like  8 or 9 Synthesis patches usually

[img]https://i.imgur.com/4wfxd0M.png[/img]

None of those esp's are in the load order at the time I create the patches. Are you saying I should create all the other patches first and then create the leveled list patch afterwards, so that it sees all those patches?

**Comment by Noggog** [comment]
You can have several Synthesis groups that rely on each other, and as long as you run them all together they should take the previous groups into consideration, even if none of them exist at the time the patcher run started

If you have multiple groups, I'd recommend running them all together (the big button at the bottom left of the app), rather than one-offs, unless you know what you're doing and why you're running one as a one-off.  This will keep them all in sync with each other more.

More reading about multiple groups:
https://github.com/Mutagen-Modding/Synthesis/wiki/Multiple-Output-Targets#running-with-multiple-groups

But also.. you might just consider putting all your patchers into one group.  Saves LO space, among other things.

**Comment by slymeasy** [comment]
> You can have several Synthesis groups that rely on each other, and as long as you run them all together they should take the previous groups into consideration, even if none of them exist at the time the patcher run started
> 
> If you have multiple groups, I'd recommend running them all together (the big button at the bottom left of the app), rather than one-offs, unless you know what you're doing and why you're running one as a one-off. This will keep them all in sync with each other more.
> 
> More reading about multiple groups: https://github.com/Mutagen-Modding/Synthesis/wiki/Multiple-Output-Targets#running-with-multiple-groups
> 
> But also.. you might just consider putting all your patchers into one group. Saves LO space, among other things.

After combining the Leveled List Resolver and the NMEE Synthesis patch together a lot more NMEE records were carried over, but there were still some that were overwritten.

**Comment by Noggog** [comment]
I dont know what each patcher's goals are, necessarily... but if you want NMEE as a patcher to "win", you can move it to run after the others so it'll have the last say.  Why are you running it early if you want its changes to always win?
